# 配置rabbitmq 基本信息
spring:
  rabbitmq:
    host: 192.168.152.128
    port: 5672
    virtual-host: /garven
    username: garven
    password: garven
    // 开启producer -> exchange 的confirm 机制
    publisher-confirms: true
